---
  host: 10.33.37.28                                       # oss ip address
  userid: 2
  orderid: 10001
  domain: 19c206ba-9d4e-44ce-8bae-0b8a5857a798            # oss domain id
  pool_name: KVMPool                                      # pool name
  epc_name: autotest

  vms:
  - name: test001
    product_spec: 2c02e128-1881-4fd8-90e5-e106c81c25b1    # vm product spec
    template: centos6.5                                   # vm template
    vm_gw: 10.25.1.1
    vm_ip:
    - vl2_name: vl2-xxx-1501
      vl2_net_index: 1
      if_index: 0
      address: 10.25.1.10

    blocks:
    - name: block001
      product_spec: bd201891-4d8d-4cdd-acc7-37136527a981    # block spec
      size: 102400
      useruuid: 79ea7075-8d47-4152-a975-54e8944b7fe1        # user spec

  - name: test002
    product_spec: 2c02e128-1881-4fd8-90e5-e106c81c25b1    # vm product spec
    template: centos6.5                                   # vm template
    vm_gw: 10.25.1.1
    vm_ip:
    - vl2_name: vl2-xxx-1501
      vl2_net_index: 1
      if_index: 0
      address: 10.25.1.11

  - name: test003
    product_spec: 2c02e128-1881-4fd8-90e5-e106c81c25b1    # vm product spec
    template: centos6.5                                   # vm template
    vm_gw: 10.25.2.1
    vm_ip:
    - vl2_name: vl2-xxx-1502
      vl2_net_index: 1
      if_index: 0
      address: 10.25.2.10

  - name: test004
    product_spec: 2c02e128-1881-4fd8-90e5-e106c81c25b1    # vm product spec
    template: centos6.5                                   # vm template
    vm_gw: 10.25.2.1
    vm_ip:
    - vl2_name: vl2-xxx-1502
      vl2_net_index: 1
      if_index: 0
      address: 10.25.2.11

  - name: test005
    product_spec: 2c02e128-1881-4fd8-90e5-e106c81c25b1    # vm product spec
    template: centos6.5                                   # vm template
    vm_gw: 192.168.0.1                                    # wan gateway
    vm_ip:
    - vl2_name: vl2-xxx-1502
      vl2_net_index: 1
      if_index: 0
      address: 10.25.2.2
    - wan_ip: 192.168.182.192                             # wan IP
      if_index: 1
      bandwidth: 10485760

  - name: test006
    product_spec: 2c02e128-1881-4fd8-90e5-e106c81c25b1    # vm product spec
    template: centos6.5                                   # vm template
    vm_gw: 192.168.0.1                                    # wan gateway
    vm_ip:
    - vl2_name: vl2-valve
      vl2_net_index: 1
      if_index: 0
      address: 192.168.182.193                            # wan IP

  vl2s:
  - name: vl2-xxx-1501
    prefix: 10.25.1.0
    netmask: 24

  - name: vl2-xxx-1502
    prefix: 10.25.2.0
    netmask: 24

  - name: vl2-valve
    prefix: 192.168.0.0                                   # wan netmask
    netmask: 16

  vgateways:
  - name: vgateway-1501
    product_spec: 26dc3b8a-1114-4385-b947-33e6af0298e1    # vgw product spec
    wan:
    - if_index: 1
      state: 1
      ip: 192.168.182.191                                 # wan IP
      bandwidth: 10485760
    lan:
    - if_index: 10
      state: 1
      vl2_name: vl2-xxx-1501
      vl2_lcuuid:
      address: 10.25.1.1

    rules:
      snat_rules:
      - sip1: 10.25.1.1
        sip2: 10.25.1.255
        dip: 192.168.182.191                              # wan IP

      dnat_rules:
      - sip: 192.168.182.191                              # wan IP
        sport: 60022
        dip: 10.25.1.11
        dport: 22

  lbs:
  - name: lb001
    lb_gw: 192.168.0.1
    product_spec: 54950fcb-6e41-49af-a02c-b48a1def3783    # lb product spec
    lb_ip:
    - wan_ip: 192.168.182.190                             # wan IP
      info: config 192.168.190.190
      if_index: 0
      bandwidth: 10485760

    - vl2_name: vl2-xxx-1502
      info: config 10.25.2.1
      vl2_net_index: 1
      address: 10.25.2.1
      if_index: 1

    lb_listener:
    - name: lb-listener-001
      protocol: http
      port: 80
      balance: roundrobin
      vms:
      - name: test003
        port: 80
        weight: 1
        state: ENABLE

      - name: test004
        port: 80
        weight: 1
        state: ENABLE

  valves:
  - name: valve-1501
    general_bandwidth: 0
    product_spec: 7200a45e-388c-4a0d-9121-5356b97936ec    # valves product spec
    wan:
    - if_index: 1
      ip: 192.168.182.193                                 # valves ip
    lan:
    - if_index: 10
      vl2_name: vl2-valve
      vl2_lcuuid:

  ips:
  - isp: 1
    number: 5
    product_spec: 19c206ba-9d4e-44ce-8bae-0b8a5857a798    # isp product spec

  - isp: 2
    number: 5
    product_spec: 19c206ba-9d4e-44ce-8bae-0b8a5857a798    # isp product spec

  bandws:
  - isp: 1
    bandw: 100
    product_spec: bb6d88c5-3f6b-4903-a91f-2649b7b3ea1e    # band product spec
  - isp: 2
    bandw: 100
    product_spec: e1cf1c6a-08ed-415e-86a3-e15595665818    # band product spec
...